### ISSUE TITLE
No transaction log written on proxy error

### ISSUE THREAD

**Issue by jschewebbn** [virtuald/ews-proxy#1]
I've been seeing log messages like the one below from time to time and I'm not getting a transaction log written, so I'm unable to debug what the problem is with the JSON.

```
2018/04/27 18:46:35 http: proxy error: unknown type WeeklyRecurrence
```

**Comment by virtuald** [comment]
The only function that returns an unknown type error is SOAP2JSON, which is only called in one place, and as you can see it calls the `OnEwsTranslationError`:  https://github.com/virtuald/ews-proxy/blob/master/ews_translation_middleware.go#L116

This implies a bug in your `OnEwsTranslationError` handler -- or do you even have one? The default is an empty function: https://github.com/virtuald/ews-proxy/blob/master/ews_translation_middleware.go#L49

**Comment by virtuald** [comment]
Are you using ews-proxy/main? It looks like it doesn't set an error handler, which would explain why you aren't seeing the errors.

**Comment by jschewebbn** [comment]
I'm using an application based on `ews-proxy/main`. That would explain why I don't have the translation handler in place.

**Comment by jschewebbn** [comment]
Adding the handler gives me transaction log files.
