### ISSUE TITLE
davmail sends XML that doesn't validate

### ISSUE THREAD

**Issue by virtuald** [virtuald/ews-proxy#9]
Not sure of the best way to deal with this. This is the cause of several bugs (particularly #7).

I wrote a validation script (`codegen/validate_xml.py`) that validates the XML against a schema. We should add to the travis tests (just added) something that validates all requests and responses to make sure we aren't doing something stupid.

**Comment by jschewebbn** [comment]
I think this is fixed with the release of davmail 4.9.0.
